ci: update build package
Signed-off-by: moabu <47318409+moabu@users.noreply.github.com>

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -10,14 +10,24 @@ permissions:
 jobs:
   publish_binary_packages:
     if: github.repository == 'GluuFederation/flex'
-    runs-on: ubuntu-20.04
+    runs-on: ${{ matrix.os }}
+    permissions:
+      id-token: write
     strategy:
       fail-fast: false
       matrix:
-        name: [ubuntu22, ubuntu20, el8, suse15]
-
+        name: [ubuntu24, ubuntu22, ubuntu20, el8, suse15]
         include:
+          - name: ubuntu24
+            os: ubuntu-latest
+            asset_suffix: ~ubuntu24.04_amd64.deb
+            build_files: deb/noble
+            asset_prefix: '_'
+            asset_path: flex
+            sign_cmd: cosign sign-blob --yes --output-certificate cert.pem --output-signature sig
+            python_version: 3.11
           - name: ubuntu22
+            os: ubuntu-20.04
             asset_suffix: ~ubuntu22.04_amd64.deb
             build_files: deb/jammy
             asset_prefix: '_'
@@ -25,6 +35,7 @@ jobs:
             sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
             python_version: "3.8"                
           - name: ubuntu20
+            os: ubuntu-20.04
             asset_suffix: ~ubuntu20.04_amd64.deb
             build_files: deb/focal
             asset_prefix: '_'
@@ -32,6 +43,7 @@ jobs:
             sign_cmd: dpkg-sig -s builder -k DE92BEF14A1A4E542F678B64DC3C790386C73900
             python_version: "3.8"
           - name: el8
+            os: ubuntu-20.04
             asset_suffix: .el8.x86_64.rpm
             build_files: rpm/el8
             asset_prefix: '-'
@@ -39,6 +51,7 @@ jobs:
             sign_cmd: rpm --addsign
             python_version: "3.6"
           - name: suse15
+            os: ubuntu-20.04
             asset_suffix: .suse15.x86_64.rpm
             build_files: rpm/suse15
             asset_prefix: '-'
@@ -59,16 +72,17 @@ jobs:
 
     - name: Getting build dependencies
       id: get_dependencies
-      run: |  
+      run: |
          mkdir -p flex/flex-src/opt/
          cp -rp temp-flex/automation/packaging/${{ matrix.build_files }}/* flex/
          cp temp-flex/flex-linux-setup/flex_linux_setup/flex_setup.py flex/flex_setup.py
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python${{ matrix.python_version }}
-         sudo apt install -y build-essential devscripts debhelper rpm dpkg-sig python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-crypto python3-distutils python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib 
+         sudo apt install -y build-essential devscripts debhelper rpm python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib
+         sudo apt install -y dpkg-sig python3-crypto python3-distutils ||  sudo apt install -y python3-distutils-extra python3-cryptography
          sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
-         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2
+         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2 || echo "failed to install psycopg2"
     - name: Import GPG key
       id: import_gpg
       continue-on-error: true
@@ -110,6 +124,10 @@ jobs:
          sed -i "s/%VERSION%/${{ steps.previoustag.outputs.version }}/g" run-build.sh
          cat run-build.sh
          sudo ./run-build.sh
+
+    - name: Install Cosign
+      uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
+
     - name: Sign package
       id: sign_package
       run : |
