chore: perpare release 5.13.0

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -5,11 +5,36 @@ on:
     tags:
     - 'v**'
     - 'nightly'
+  workflow_dispatch:
+    inputs:
+      target_tag:
+        description: 'The release tag to upload assets to (e.g., v1.0.1 or nightly). Required.'
+        required: true
+        type: string
+      run_binary_packages:
+        description: 'Run the "publish_binary_packages" job?'
+        required: true
+        type: boolean
+        default: true
+      jans_branch:
+        description: 'The --jans-branch to use for the setup script.'
+        required: true
+        type: string
+        default: 'main'
+      jans_setup_branch:
+        description: 'The --jans-setup-branch to use for the setup script.'
+        required: true
+        type: string
+        default: 'main'
+
 permissions:
   contents: read
+
 jobs:
   publish_binary_packages:
-    if: github.repository == 'GluuFederation/flex'
+    if: |
+      github.repository == 'GluuFederation/flex' &&
+      (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.run_binary_packages))
     runs-on: ${{ matrix.os }}
     permissions:
       id-token: write
@@ -73,16 +98,16 @@ jobs:
     - name: Getting build dependencies
       id: get_dependencies
       run: |
-         mkdir -p flex/flex-src/opt/
-         cp -rp temp-flex/automation/packaging/${{ matrix.build_files }}/* flex/
-         cp temp-flex/flex-linux-setup/flex_linux_setup/flex_setup.py flex/flex_setup.py
-         sudo add-apt-repository ppa:deadsnakes/ppa
-         sudo apt-get update
-         sudo apt-get install -y python${{ matrix.python_version }}
-         sudo apt install -y build-essential devscripts debhelper rpm python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib
-         sudo apt install -y dpkg-sig python3-crypto python3-distutils ||  sudo apt install -y python3-distutils-extra python3-cryptography
-         sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
-         sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2 || echo "failed to install psycopg2"
+        mkdir -p flex/flex-src/opt/
+        cp -rp temp-flex/automation/packaging/${{ matrix.build_files }}/* flex/
+        cp temp-flex/flex-linux-setup/flex_linux_setup/flex_setup.py flex/flex_setup.py
+        sudo add-apt-repository -y ppa:deadsnakes/ppa
+        sudo apt-get update
+        sudo apt-get install -y python${{ matrix.python_version }}
+        sudo apt install -y build-essential devscripts debhelper rpm python3-dev python3-requests python3-ruamel.yaml python3-pymysql python3-prompt-toolkit python${{ matrix.python_version }}-distutils libpq-dev python${{ matrix.python_version }}-dev apache2 rsyslog python3-urllib3 python3-certifi postgresql postgresql-contrib
+        sudo apt install -y dpkg-sig python3-crypto python3-distutils ||  sudo apt install -y python3-distutils-extra python3-cryptography
+        sudo cp -r /usr/lib/python3/dist-packages /usr/lib/python${{ matrix.python_version }}/
+        sudo python${{ matrix.python_version }} -m pip install psycopg2-binary psycopg2 || echo "failed to install psycopg2"
     - name: Import GPG key
       id: import_gpg
       continue-on-error: true
@@ -98,11 +123,17 @@ jobs:
     - name: Get latest tag
       id: previoustag
       run: |
-        echo "tag=$(echo ${{ github.event.ref }} | cut -d '/' -f 3)" >> $GITHUB_OUTPUT
-        if [[ ${{ github.event.ref }} == 'refs/tags/nightly' ]]; then
+        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+          TAG_NAME="${{ inputs.target_tag }}"
+        else
+          TAG_NAME=$(echo "${{ github.event.ref }}" | cut -d '/' -f 3)
+        fi
+
+        echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
+        if [[ "${TAG_NAME}" == "nightly" ]]; then
           echo "version=0.0.0-nightly" >> $GITHUB_OUTPUT
         else
-          echo "version=$(echo ${{ github.event.ref }} | cut -d 'v' -f 2)-stable" >> $GITHUB_OUTPUT
+          echo "version=$(echo "${TAG_NAME}" | sed 's/^v//')-stable" >> $GITHUB_OUTPUT
         fi
         echo "PACKAGE_PREFIX=flex" >> ${GITHUB_ENV}
 
@@ -113,17 +144,17 @@ jobs:
     - name: Running install and build
       id: run_build
       run: |
-         cd flex/
-         sudo python${{ matrix.python_version }} flex_setup.py --jans-branch="main" --jans-setup-branch="main" -download-exit -yes --keep-downloads --keep-setup -force-download
-         cp -r /opt/dist flex-src/opt/
-         cp -r /opt/jans flex-src/opt/
-         touch flex-src/opt/jans/jans-setup/package
-         rm -rf install.py install jans-cli
-         rm -rf flex-src/opt/jans/jans-setup/logs/setup.log
-         rm -rf flex-src/opt/jans/jans-setup/logs/setup_error.log
-         sed -i "s/%VERSION%/${{ steps.previoustag.outputs.version }}/g" run-build.sh
-         cat run-build.sh
-         sudo ./run-build.sh
+        cd flex/
+        sudo python${{ matrix.python_version }} flex_setup.py --jans-branch="${{ inputs.jans_branch }}" --jans-setup-branch="${{ inputs.jans_setup_branch }}" -download-exit -yes --keep-downloads --keep-setup -force-download
+        cp -r /opt/dist flex-src/opt/
+        cp -r /opt/jans flex-src/opt/
+        touch flex-src/opt/jans/jans-setup/package
+        rm -rf install.py install jans-cli
+        rm -rf flex-src/opt/jans/jans-setup/logs/setup.log
+        rm -rf flex-src/opt/jans/jans-setup/logs/setup_error.log
+        sed -i "s/%VERSION%/${{ steps.previoustag.outputs.version }}/g" run-build.sh
+        cat run-build.sh
+        sudo ./run-build.sh
 
     - name: Install Cosign
       uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
@@ -133,7 +164,7 @@ jobs:
       run : |
         ls ${{github.workspace}}/${{ matrix.asset_path }}
         sudo mv ${{github.workspace}}/${{ matrix.asset_path }}/flex* ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }} || echo "no need to rename"
-        echo '%_gpg_name moauto (automation) <54212639+mo-auto@users.noreply.github.com>' >> ~/.rpmmacros      
+        echo '%_gpg_name moauto (automation) <54212639+mo-auto@users.noreply.github.com>' >> ~/.rpmmacros
         ${{ matrix.sign_cmd }} ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}
         gpg --armor --detach-sign ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}
         ls ${{github.workspace}}/${{ matrix.asset_path }}
@@ -147,7 +178,7 @@ jobs:
 
     - name: Upload binaries to release
       id: upload_binaries
-      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
+      uses: svenstaro/upload-release-action@1beeb57c19a9242f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         repo_token: ${{ secrets.MOWORKFLOWTOKEN }}
         file: ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}
@@ -156,7 +187,7 @@ jobs:
         overwrite: true
     - name: Upload checksum to release
       id: upload_shas
-      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
+      uses: svenstaro/upload-release-action@1beeb572c19a9242f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         repo_token: ${{ secrets.MOWORKFLOWTOKEN }}
         file: ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}.sha256sum
@@ -165,7 +196,7 @@ jobs:
         overwrite: true
     - name: Upload sig to release
       id: upload_sigs
-      uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
+      uses: svenstaro/upload-release-action@1beeb57c19a9242f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         repo_token: ${{ secrets.MOWORKFLOWTOKEN }}
         file: ${{github.workspace}}/${{ matrix.asset_path }}/flex${{ matrix.asset_prefix }}${{ steps.previoustag.outputs.version }}${{ matrix.asset_suffix }}.asc
