feat(cloud-native): extend jans persistence-loader image to add more files required by Flex installation (#2579)
* feat(cloud-native): extend jans persistence-loader image to add more files required by Flex installation

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* ci(cloud-native): add doker-persistence-loader build

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* feat(chart): introduce ghcr.io/gluufederation/flex/persistence-loader image into the charts

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* chore: update JANS_SOURCE_VERSION

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* chore: minor refactoring

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* chore: minor Makefile changes

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* chore: remove empty hadolint file

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* ci: ensure all-in-image is built after required images pulled successfully

Signed-off-by: iromli <isman.firmansyah@gmail.com>

* ci: avoid indefinite loop while pulling required images

Signed-off-by: iromli <isman.firmansyah@gmail.com>

---------

Signed-off-by: iromli <isman.firmansyah@gmail.com>

diff --git a/.github/workflows/docker_build_image.yml b/.github/workflows/docker_build_image.yml
--- a/.github/workflows/docker_build_image.yml
+++ b/.github/workflows/docker_build_image.yml
@@ -15,9 +15,9 @@ on:
   workflow_dispatch:
     inputs:
       services:
-        description: 'One or set of the docker images. Format as following: "docker-admin-ui docker-flex-monolith docker-flex-all-in-one"'
+        description: 'One or set of the docker images. Format as following: "docker-admin-ui docker-persistence-loader docker-flex-monolith docker-flex-all-in-one"'
         required: true
-        default: 'docker-admin-ui docker-flex-monolith docker-flex-all-in-one'
+        default: 'docker-admin-ui docker-persistence-loader docker-flex-monolith docker-flex-all-in-one'
       gluu_version:
         description: 'The war version to build the image off'
         required: false
@@ -42,7 +42,7 @@ jobs:
     strategy:
       max-parallel: 8
       matrix:
-        docker-images: ["admin-ui", "flex-monolith", "flex-all-in-one"]
+        docker-images: ["admin-ui", "persistence-loader", "flex-monolith", "flex-all-in-one"]
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
@@ -59,6 +59,7 @@ jobs:
           sparse-checkout: |
             automation
             docker-admin-ui
+            docker-persistence-loader
             docker-flex-monolith
             docker-flex-all-in-one
       - name: Check docker directories that changed
@@ -68,7 +69,7 @@ jobs:
           DEFAULT_ALL=${{ github.event.inputs.services }}
           if [ -z "$DEFAULT_ALL" ]
           then
-            DEFAULT_ALL="docker-admin-ui docker-flex-monolith docker-flex-all-in-one"
+            DEFAULT_ALL="docker-admin-ui docker-persistence-loader docker-flex-monolith docker-flex-all-in-one"
           else
             echo "$DEFAULT_ALL"
           fi
@@ -136,15 +137,25 @@ jobs:
           echo "build=${BUILD}" >> $GITHUB_OUTPUT
           if [[ "flex-all-in-one" =~ "${{ matrix.docker-images }}" ]]; then
             echo "Waiting for all images to be built before building the all-in-one image"
-            while true; do
-              echo "Attempting to pull the Docker image"
-              if docker pull ghcr.io/$REPOSITORY/admin-ui:$VERSION; then
-                echo "Docker image pulled successfully"
-                break
-              else
-                echo "Failed to pull Docker image, retrying in 20 seconds"
-                sleep 20
-              fi
+            TEMP_IMG="admin-ui persistence-loader"
+            for img in $TEMP_IMG; do
+              max_retries=30
+              retry_count=0
+              while true; do
+                echo "Attempting to pull $img image"
+                if docker pull ghcr.io/$REPOSITORY/$img:$VERSION; then
+                  echo "$img image pulled successfully"
+                  break
+                else
+                  retry_count=$((retry_count + 1))
+                  if [ $retry_count -ge $max_retries ]; then
+                    echo "Failed to pull $img image after $max_retries attempts"
+                    exit 1
+                  fi
+                  echo "Failed to pull $img image, retrying in 20 seconds (attempt $retry_count/$max_retries)"
+                  sleep 20
+                fi
+              done
             done
           fi
 
